/*******************************************************************************
 * Copyright (c) 2014 Uimirror.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Uimirror license
 * which accompanies this distribution, and is available at
 * http://www.uimirror.com/legal
 *
 * Contributors:
 * Uimirror Team
 *******************************************************************************/
package com.uimirror.auth;

import com.uimirror.core.auth.bean.AccessToken;
import com.uimirror.core.auth.controller.AuthenticationProvider;

/**
 * Stores the authentication token generated by {@linkplain AuthenticationProvider#getAuthenticateToken(com.uimirror.core.auth.bean.Authentication)}
 * Defines the contract that user needs to store the generated token for the further
 * reference
 * 
 * @author Jay
 */
public interface AuthStoreProvider extends AuthenticationProvider{

	/**
	 * Stores the generated token for the further reference
	 * @param token
	 */
	void storeToken(AccessToken token);
}
